version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: trivasoft
      POSTGRES_USER: trivasoft
      POSTGRES_PASSWORD: Triva12748294!
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules  # Prevents overwriting node_modules
    depends_on:
      - backend


volumes:
  pgdata:
