# Generated by Django 4.2.9 on 2024-11-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAssetsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAssetsPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('AZN', 'AZN'), ('TL', 'TL'), ('RBL', 'RBL'), ('EUR', 'EUR')], default='AZN', max_length=3)),
                ('currency_rate', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('ygb_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ygb_payment', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('customs_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('import_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('logistic_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAssetsPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Invoice Number')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paid Amount')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remaining Balance')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='issued', max_length=20, verbose_name='Status')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Issued Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetsPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customs_fee_share', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('import_fee_share', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('logistics_expense_share', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('final_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.fixedassets')),
                ('fixed_asset_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='assets.fixedassetspurchase')),
            ],
        ),
    ]
