# Generated by Django 4.2.9 on 2024-11-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landedcost',
            name='apply_vat',
            field=models.BooleanField(default=True, help_text='Indicates if VAT should be applied to this cost'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='converted_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='vat_applicable_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost that is applicable for VAT calculation', max_digits=10),
        ),
    ]
