# Generated by Django 4.2.9 on 2024-11-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchase', '0004_landedcost_apply_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceive',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receives', to='inventory.warehouse'),
        ),
    ]
