# Generated by Django 4.2.9 on 2024-11-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchasereceive_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='payment_status',
        ),
    ]
