# Generated by Django 4.2.9 on 2024-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER', 'Transfer'), ('EXPECTED_IN', 'Expected Stock In'), ('EXPECTED_OUT', 'Expected Stock Out'), ('RESERVED_IN', 'Reserved Stock In'), ('RESERVED_OUT', 'Reserved Stock Out'), ('CANCELLED_PURCHASE', 'Cancelled Purchase'), ('CANCELLED_SALE', 'Cancelled Sale')], max_length=20),
        ),
    ]
