# Generated by Django 4.2.9 on 2024-11-10 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchasereceive_warehouse'),
        ('inventory', '0003_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_receive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchasereceive'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase'),
        ),
    ]
