# Generated by Django 4.2.9 on 2024-11-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_purchase_receive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER', 'Transfer'), ('EXPECTED', 'Expected Stock'), ('RESERVED', 'Reserved Stock'), ('CANCELLED_PURCHASE', 'Cancelled Purchase'), ('CANCELLED_SALE', 'Cancelled Sale')], max_length=20),
        ),
    ]
