# Generated by Django 4.2.9 on 2024-11-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Account Number')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('AZN', 'Azerbaijani Manat'), ('TL', 'Turkish Lira')], default='USD', max_length=3, verbose_name='Currency')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, unique=True, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('TREASURY', 'Treasury Account'), ('SUB', 'Sub Cash Account')], default='SUB', max_length=8, verbose_name='Account Type')),
                ('currency', models.CharField(choices=[('AZN', 'Azerbaijani Manat')], default='AZN', max_length=3, verbose_name='Currency')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Cash Account',
                'verbose_name_plural': 'Cash Accounts',
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash Account')], max_length=4, verbose_name='Payment Method')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='FixedAssetsPurchaseInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash Account')], max_length=4, verbose_name='Payment Method')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash Account')], max_length=4, verbose_name='Payment Method')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash Account')], max_length=4, verbose_name='Payment Method')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxDepositAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Account Number')),
                ('currency', models.CharField(choices=[('AZN', 'Azerbaijani Manat')], default='AZN', max_length=3, verbose_name='Currency')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tax Deposit Account',
                'verbose_name_plural': 'Tax Deposit Accounts',
            },
        ),
    ]
